MEM = "1024"
CPU = 1

Vagrant.configure("2") do |config|
  
    # Configuration for the first machine (Server)
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = MEM
      vb.cpus = CPU
    end
  
    config.vm.define "jnguyenS" do |server|
      server.vm.hostname = "jnguyenS"
      server.vm.box = "generic/alpine318"
      server.vm.synced_folder ".", "/vagrant"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", privileged: true, path: "scripts/master_node.sh", args: ["192.168.56.110"]
      server.vm.provision "shell", inline: <<-SHELL
        kubectl apply -f /vagrant/confs/deployment.yaml
      SHELL
    end
end