# -*- mode: ruby -*-
# vi: set ft=ruby :

MEM = "1024"
CPU = 1 

Vagrant.configure("2") do |config|
  
  # Configuration for the first machine (Server)

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEM
    vb.cpus = CPU
  end

  config.vm.define "jnguyenS" do |server|
    server.vm.hostname = "jnguyenS"
    server.vm.box = "generic/alpine318"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", privileged: true, path: "scripts/master_node.sh", args: ["192.168.56.110"]
  end

  # Configuration for the second machine (ServerWorker)
  config.vm.define "jnguyenSW" do |serverworker|
    serverworker.vm.box = "generic/alpine318"
    serverworker.vm.hostname = "jnguyenSW"
    serverworker.vm.synced_folder ".", "/vagrant"
    serverworker.vm.network "private_network", ip: "192.168.56.111"
    serverworker.vm.provision "shell", privileged: true, path: "scripts/worker_node.sh"

  end

  # SSH Key Configuration for passwordless SSH
  # config.ssh.insert_key = false
  # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

end
